### ISSUE TITLE
AMDirT commands always print a cache_data_api warning

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#110] opened 2023-04-18 11:08 UTC
```
(amdirt) james@bionb103:~$ AMDirT --help
2023-04-18 13:07:37.864 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.866 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.866 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.867 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.867 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.868 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.868 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-04-18 13:07:37.869 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
Usage: AMDirT [OPTIONS] COMMAND [ARGS]...

  AMDirT: Performs validity check of ancientMetagenomeDir datasets
  Authors: AMDirT development team and the SPAAM community
  Homepage & Documentation: https://github.com/SPAAM-community/AMDirT
  

Options:
  --version  Show the version and exit.
  --verbose  Verbose mode
  --help     Show this message and exit.

Commands:
  autofill  Autofills library and/or sample table(s) using ENA API and...
  convert   Converts filtered samples and libraries tables to eager,...
  merge     Merges new dataset with existing table 
  validate  Run validity check of ancientMetagenomeDir datasets...
  viewer    Launch interactive filtering tool
```

**Comment by maxibor** [comment] 2023-04-18 13:11
What kind of systems do you have ?
I can't reproduce

**Comment by jfy133** [comment] 2023-04-19 06:39
OK I just tried after wiping everything and installing without the `environemnt.yml` and directrly with pip, and I still get the same warning message. Maybe we should try and find someone else to test out the installation as well and see if someone else gets it?

It is just a warning but it could scare users as this streamlit warning is coming even though the user isn't running the `viewer` command (in which context it woudl be fine)

**Comment by jfy133** [comment] 2023-04-19 08:47
According to teh conda environment of `python 3.9` + `pip intall -e .` + `cd docs && pip install -r requirements`

```
(amdirt) james@bionb103:~/git/spaam-community/AMDirT$ conda list
# packages in environment at /home/james/bin/miniconda3/envs/amdirt:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alabaster                 0.7.13                   pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
amdirt                    1.4                       dev_0    <develop>
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
blinker                   1.6.2                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.2                    pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.5.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.22.3                   pypi_0    pypi
openssl                   3.1.0                h0b41bf4_0    conda-forge
packaging                 23.1                     pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1               pyhd8ed1ab_0    conda-forge
protobuf                  3.20.3                   pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pydeck                    0.8.1b0                  pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.9.16          h2782a2a_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-decouple           3.8                      pypi_0    pypi
python-dotenv             0.19.2                   pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
recommonmark              0.7.1                    pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
rich                      12.2.0                   pypi_0    pypi
setuptools                62.0.0                   pypi_0    pypi
simplejson                3.17.6                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.5.0                    pypi_0    pypi
sphinx-click              3.1.0                    pypi_0    pypi
sphinx-rtd-theme          1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
streamlit                 1.21.0                   pypi_0    pypi
streamlit-aggrid          0.3.4.post3              pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.3                      pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
tzlocal                   4.3                      pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
validators                0.20.0                   pypi_0    pypi
watchdog                  2.1.7                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xmltodict                 0.12.0                   pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.15.0                   pypi_0    pypi

```

**Comment by maxibor** [comment] 2023-04-19 10:46
Apparently a known issue, that should be fixed with the next release of streamlit since a PR fix was already merged https://github.com/streamlit/streamlit/issues/6440

I would leave it aside for now, and just update the streamlit version requirement once they release a new version

**Comment by maxibor** [comment] 2023-05-03 12:35
I've opened an issue on streamlit repo https://github.com/streamlit/streamlit/issues/6620

**Closed** 2023-12-15 13:33 UTC
Labels: need upstream fix
